spring:
  application:
    name: food_store_backend
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/foodstr
    username: foodroot
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: foodstr
server:
  port: 8888