name: Build and Test project
on: 
  push:
    branches: ["develop"]
jobs:
  check-develop-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5.0.0

      - name: Setup Java Project
        uses: actions/setup-java@v3.14.1
        with: 
          distribution: 'temurin'
          java-version: '21'
    
      - name: Clean & Build Maven Project
        working-directory: food_store_backend
        run: |
          echo "Starting Maven Clean & Build..."
          chmod +x mvnw
          ./mvnw clean package -DskipTests
